paginate: 10
plugins: [jekyll-paginate]

name: Seccubus
description: Easy Automated vulnerability scanning and reporting
url: https://www.seccubus.com
baseurl: 
timezone: Europe/Amsterdam
future: true

permalink: pretty
paginate_path: "news/:num/"
highlighter: rouge
markdown: kramdown
redcarpet:
    extensions:
        - no_intra_emphasis
        - autolink
        - strikethrough
        - fenced_code_blocks
